gis4wrf/core/__init__.py, gis4wrf/core/downloaders/plugin_version.py, gis4wrf/plugin/plugin.py
When we release a new version on the QGIS repository we want to notify the user that a new version is available.  This enhancement  is used to check that the GIS4WRF version installed on the system is the latest, else we prompt the user with a message asking to update to the latest version.
=> Check plugin version on activation of plugin

gis4wrf/core/project.py, gis4wrf/plugin/broadcast.py, gis4wrf/plugin/options.py, gis4wrf/plugin/ui/tab_simulation.py, gis4wrf/plugin/ui/widget_datasets.py, gis4wrf/plugin/ui/widget_geo.py, gis4wrf/plugin/ui/widget_met.py, gis4wrf/plugin/ui/widget_run.py
This fixes #18.
- When opening/creating a project, the message "WPS/WRF not found, functionality will be reduced." appears in the message bar when WPS or WRF paths are not set. Clicking on the various "Run" buttons that depend on WPS/WRF now leads to an error message (plain exception currently).
- If a project was created without WPS set, then the geo datasets selector is empty, but will be populated as soon as WPS is configured in the options.
Note that I didn't bother surfacing the "Run" button errors as proper message bar messages but rather plain exceptions. Since pressing those buttons without WRF/WPS is a nonsense thing to do anyway it should be fine for now. At some point we can think about a bigger strategy on error handling, including custom exception classes and more …
=> Allow to create/open projects without a WPS/WRF installation set

gis4wrf/bootstrap.py
See https://github.com/yaml/pyyaml/issues/126.
=> Bump pyyaml dependency to 3.13 to include Python 3.7 fix

gis4wrf/core/readers/namelist.py, gis4wrf/core/transforms/wps_namelist_to_project.py, gis4wrf/plugin/broadcast.py, gis4wrf/plugin/ui/tab_simulation.py, gis4wrf/plugin/ui/widget_domains.py
This PR solves #27. We adds support for importing existing namelist.wps into GIS4WRF using the `Import from namelist`  button under `Simulation` > `Domain`. Domains are automatically visualised. We currently support `lat-lon` and `lambert` projections.
=> Add support for importing existing namelist.wps (closes #27)

gis4wrf/core/project.py, gis4wrf/plugin/options.py, gis4wrf/plugin/plugin.py, gis4wrf/plugin/ui/dialog_custom_met_dataset.py, gis4wrf/plugin/ui/helpers.py, gis4wrf/plugin/ui/options.py, gis4wrf/plugin/ui/widget_datasets.py
This implements #23.
There's a new button in the met dataset selector. Also, "Current configuration" shows a different text if a custom dataset is used:
Clicking on the button opens a dialog for defining the custom dataset:
Adding a folder recursively adds all files in it. Unwanted files can be removed again with "Remove selected".
Note that the custom dataset information is stored in the project but is not added to the "Available datasets" list from the first screenshot. This was simpler to handle and shouldn't present any limitation.
=> Allow to use custom met datasets

gis4wrf/core/downloaders/dist.py, gis4wrf/plugin/ui/helpers.py, gis4wrf/plugin/ui/options.py
Now we have progress bars everywhere! Well, except for running WRF, that might be fun...
=> Show progress during WRF/WPS distribution download

gis4wrf/plugin/ui/helpers.py, gis4wrf/plugin/ui/options.py, gis4wrf/plugin/ui/widget_run.py
The check is simplistic but should be good enough for our purposes. It checks if the executable path contains `-nompi` (which the plugin uses when downloading/extracting the serial distributions) and errors if MPI was enabled in the plugin. Note that running MPI-enabled WRF/WPS distributions without MPI enabled (without mpiexec) is normally harmless and just runs them serially, so this condition is not checked.
Also, to make it clearer, I changed the download buttons to include the WRF/WPS version:
=> Error if MPI is enabled but pre-built distribution without MPI support is used

gis4wrf/core/constants.py, gis4wrf/plugin/plugin.py
This works like the plugin version check, getting triggered 2min after QGIS start.
Is the wording ok?
=> Notify user if old pre-built WRF/WPS distributions are used

gis4wrf/plugin/options.py, gis4wrf/plugin/ui/options.py
This implements #82. The original suggestion mentioned Linux and macOS only, but I see no issue following the same logic on Windows, so this PR does it for all systems.
The PR also contains a little refactoring around calling `.save()` and some typo fixes.
=> Proactively enable MPI if available when user hasn't setup WRF/WPS distribution yet

CHANGELOG.txt, gis4wrf/metadata.txt
This is a hot-fix to minimise #98. Momentarily fix the max QGIS version to 3.2.x so to avoid problem on Windows.
=> 0.13.1 HotFix Release

CHANGELOG.txt, gis4wrf/core/constants.py, gis4wrf/core/project.py, gis4wrf/core/transforms/project_to_wps_namelist.py, gis4wrf/core/transforms/wps_binary_to_gdal.py, gis4wrf/core/transforms/wps_namelist_to_project.py, gis4wrf/metadata.txt, gis4wrf/plugin/ui/widget_domains.py
This fixes #116 and also adds the two missing WRF projections.
**Note:** The gis4wrf [tutorial](https://gis4wrf.github.io/tutorials/) has to be changed as well because standard longitude is now required for Lambert.
=> Fix standard longitude for Lambert projection & add Polar Stereographic and Mercator

gis4wrf/bootstrap.py
The latest Qgis 3.4 ltr version has 'python-qgis-ltr.bat' instead of 'python-qgis.bat'
=> Fix deps install on Windows using the latest Qgis 3.4 ltr

gis4wrf/plugin/ui/widget_run.py
For some reason, the filter we used before was incorrect but worked on Windows and macOS, but not on Linux. This PR changes the filter to the [correct format](https://doc-snapshots.qt.io/qt5-5.9/qfiledialog.html#getOpenFileName).
=> Fix incorrect filename filter in file open dialogs (fixes #125)

gis4wrf/core/transforms/wps_binary_to_gdal.py, gis4wrf/core/writers/wps_binary.py
Fixes #135.
When scale/offset information is not available for a layer to be converted to WPS binary, then previously this wasn't handled and just raised an assertion error. Now we assume scale=1 offset=0 in that case and carry on. Unfortunately, [GDAL's docs](https://www.gdal.org/classGDALRasterBand.html#a11e59146b02d52127c8427cccc37683d) are a bit vague on when this may happen ("a boolean to use to indicate if the returned value is meaningful or not"), but it's probably fine...
The other change is when the CRS is missing. In that case we would fail previously, whereas now we simply assume EPSG:4326 (WGS84) as fall-back which will be good enough in those cases. Note that this is a little unfortunate since the user gets prompted by QGIS when opening the layer/file if the CRS is missing, …
=> WPS binary: fix handling of unknown scale, offset, CRS

gis4wrf/bootstrap.py
The old artifacts went past the retention date and prevented successful gis4wrf installation on Windows.
This also updates wrf-python from 1.1.2 to 1.3.2.
Fixes #138.
Needs testing before merging/release.
=> Update wrf-python wheel urls for Windows

gis4wrf/bootstrap.py
This fixes #153. Binary distributions of wrf-python (a dependency of gis4wrf) are still not released on PyPI. In order to use it on Windows we had hard-coded a direct path to the package files stored on Appveyor which however expired such that the files are not available anymore and the installation now fails on Windows. This PR changes the URLs to use the permanently stored wheels from https://github.com/NCAR/wrf-python-wheels.
=> Update wrf-python whl URLs (Windows)

gis4wrf/core/readers/grib_metadata.py
This fixes #151. I reproduced/tested it manually by downloading two met datasets with different variables and then copying a file from one into the other dataset folder.
=> Allow GRIB files with different vars in one folder

gis4wrf/core/crs.py, tests/core/test_crs.py
Fixes #152.
When using GDAL 3, then the lat/lon axis order is flipped in some cases, to be more standards compliant. This PR restores the traditional order if GDAL 3 is used so that the code works both in old and new GDAL versions.
I added two new tests of which `test_projection_origin` reproduces the issue.
=> Fix lat/lon axis order when using gdal 3

gis4wrf/bootstrap.py
wrf-python is not maintained anymore. This is a problem for Windows since no binary wheels are published. On Linux and macOS, building from source generally works fine. This PR removes installation of wrf-python for Windows. It fixes #175.
=> Remove wrf-python wheel install on Windows

CHANGELOG.txt, gis4wrf/core/project.py
Fixes #183.
Note that this did not lead to incorrect simulations as `real` picks the right met_em* files anyway. The issue is more with gis4wrf code that tries to read some metadata from the met_em* files to populate the `num_metgrid_levels` option in the namelist for running wrf. If the number is incorrect, real.exe will just exit. Cleaning up old output files before running metgrid fixes this issue and is good style generally.
=> Cleanup metgrid outputs to avoid issue re-running wrf

gis4wrf/core/readers/grib_metadata.py
Fixes #182.
Notes:
For analysis datasets valid and ref time is the same in the GRIB files.
For forecast datasets they are different and valid time is the one that has to be used in the WRF namelist. Previously we used ref time in all cases.
=> Use valid time instead of ref time from GRIB files

gis4wrf/core/project.py
Fixes #164.
In theory, users can override the default filenames with e.g. `gfdda_inname` but this PR should be good enough as people likely won't do that.
=> Don't clean wrffdda_*, wrfsfdda_* and wrflowinp_* files before running wrf

gis4wrf/plugin/ui/browser_nml_schema.py
E.g. `wrffdda_d<domain>` would be displayed as `wrffdda_d` without escaping `<` and `>`.
=> HTML-escape content in NML schema viewer

gis4wrf/plugin/plugin.py
Fixes #213.
This was caused by a backwards-incompatible renaming of a log level in QGIS 3.20, see https://github.com/qgis/QGIS/issues/42996.
=> Fix logging in QGIS 3.20

gis4wrf/plugin/plugin.py
Fixes https://github.com/GIS4WRF/gis4wrf/issues/223.
Note: 3.16 worked previously, so this must have been due to some breaking change in a patch version in the 3.16 series. The new code is robust and will work on the old and new behaviour.
=> Fix log level on QGIS 3.16 preventing plugin loading

gis4wrf/bootstrap.py
The automatic Python package installation technique (bootstrapping) used in GIS4WRF works on Ubuntu 20.04 (and maybe earlier) but then fails at import because the wrong import path is added. The PR fixes that. Once merged, the installation docs can be simplified to be like the Windows ones (just install QGIS).
Related: https://github.com/GIS4WRF/gis4wrf/issues/233
Note that earlier Ubuntu versions had a problem with the bootstrapping method used here (`pip install --prefix ..` wasn't supported) but this seems to have been fixed at some point.
=> Fix Ubuntu bootstrap
